// THESIS: the core of the web, named — a single founder, not a team page.
// OWN-WORLD: the hub's world (graphite ground, the studio's amber signal,
// Space Grotesk/IBM Plex Sans), with each principle carrying the same node
// marker the web and the lineup use rather than a bullet.
// STORY: a visitor understands one person builds and stands behind every
// product in the lineup. FIRST VIEWPORT: the headline stating that plainly,
// then the principles as stops. No photo, no team grid — kept deliberately
// generic per brief. FORM: extends the hub's established world; no new
// direction roll.
import 'package:flutter/material.dart';

import '../app/app_icon.dart';
import '../app/motion.dart';
import '../app/site_shell.dart';
import '../data/activity.dart';
import '../data/products.dart';
import '../theme/sl_theme.dart';

class AboutPage extends StatelessWidget {
  const AboutPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const SiteShell(
      children: [
        _AboutHero(),
        _Activity(),
        SLRule(),
        _WhereItWent(),
        SLRule(),
        _Principles(),
      ],
    );
  }
}

class _AboutHero extends StatelessWidget {
  const _AboutHero();

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.of(context).size.width;
    final headlineSize = width < 640 ? 44.0 : 80.0;
    return SLPage(
      padding: EdgeInsets.fromLTRB(24, width < 640 ? 48 : 96, 24, 56),
      child: FadeSlideIn(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Keeps the section at full measure; without it the Column
            // shrink-wraps and the enclosing Center pushes it inward.
            const SizedBox(width: double.infinity),
            Text(
              'One person.\nOne studio.',
              style: SLType.display(headlineSize).copyWith(height: 0.95),
            ),
            const SizedBox(height: 24),
            ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 560),
              child: Text(
                'Supremo Labs is built by a single founder who would rather '
                'ship one considered product than ten unfinished ones. Every '
                'app in the lineup passes through the same hands and the same '
                'standard before it goes out.',
                style: SLType.body(17),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ------------------------------------------------------------- activity

DateTime _day(String key) => DateTime.parse(key);

String _key(DateTime d) =>
    '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

/// Totals read straight off the generated git history.
({int commits, int days, int streak, int best}) _totals() {
  final keys = commitDays.keys.toList()..sort();
  var streak = 0, run = 0, best = 0;
  DateTime? prev;
  for (final k in keys) {
    final d = _day(k);
    run = prev != null && d.difference(prev).inDays == 1 ? run + 1 : 1;
    if (run > streak) streak = run;
    if (commitDays[k]! > best) best = commitDays[k]!;
    prev = d;
  }
  return (
    commits: commitDays.values.fold(0, (a, b) => a + b),
    days: keys.length,
    streak: streak,
    best: best,
  );
}

/// The commit grid: every commit across the studio's repositories over the
/// last year, one square a day. Real history, regenerated by
/// `tool/gen_activity.py` — not decoration.
class _Activity extends StatelessWidget {
  const _Activity();

  @override
  Widget build(BuildContext context) {
    final narrow = MediaQuery.sizeOf(context).width < 760;
    final t = _totals();
    Widget stat(String label, int value) => Expanded(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _Count(value, style: SLType.display(narrow ? 40 : 64)),
          const SizedBox(height: 4),
          Text(label.toUpperCase(), style: SLType.label(SLColors.inkMuted)),
        ],
      ),
    );
    return SLPage(
      padding: EdgeInsets.fromLTRB(24, 0, 24, narrow ? 56 : 88),
      child: FadeSlideIn(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Divider(color: SLColors.hairline, height: 1, thickness: 1),
            SizedBox(height: narrow ? 40 : 64),
            Row(
              children: [
                const PulseDot(color: SLColors.accent, size: 6),
                const SizedBox(width: 10),
                Text(
                  'THE LAST TWELVE MONTHS',
                  style: SLType.eyebrow(SLColors.accent),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(
              'Shipping, most days.',
              style: SLType.display(narrow ? 44 : 64),
            ),
            const SizedBox(height: 32),
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                stat('Commits', t.commits),
                stat('Days shipped', t.days),
                stat('Longest run', t.streak),
              ],
            ),
            SizedBox(height: narrow ? 32 : 48),
            const _CommitGrid(),
            const SizedBox(height: 16),
            Text(
              'Every commit across all repositories, from git history.',
              style: SLType.body(13),
            ),
          ],
        ),
      ),
    );
  }
}

/// A number that counts up when it scrolls into view.
class _Count extends StatelessWidget {
  final int value;
  final TextStyle style;
  const _Count(this.value, {required this.style});

  @override
  Widget build(BuildContext context) {
    final reduce = MediaQuery.disableAnimationsOf(context);
    return WhenVisible(
      builder: (context, visible) => TweenAnimationBuilder<double>(
        tween: Tween(
          begin: reduce ? value.toDouble() : 0,
          end: visible ? value.toDouble() : (reduce ? value.toDouble() : 0),
        ),
        duration: const Duration(milliseconds: 1600),
        curve: const Cubic(0.16, 1, 0.3, 1),
        builder: (_, v, _) => Text('${v.round()}', style: style),
      ),
    );
  }
}

const _weeks = 53;
const _gap = 3.0;

class _CommitGrid extends StatefulWidget {
  const _CommitGrid();

  @override
  State<_CommitGrid> createState() => _CommitGridState();
}

class _CommitGridState extends State<_CommitGrid>
    with SingleTickerProviderStateMixin {
  late final _c = AnimationController(
    vsync: this,
    duration: const Duration(milliseconds: 2200),
  );
  final _scroll = ScrollController();
  int? _hover; // week * 7 + day

  @override
  void dispose() {
    _c.dispose();
    _scroll.dispose();
    super.dispose();
  }

  DateTime _date(int i) => activityStart.add(Duration(days: i));

  @override
  Widget build(BuildContext context) {
    final reduce = MediaQuery.disableAnimationsOf(context);
    return WhenVisible(
      builder: (context, visible) {
        if (visible && !_c.isAnimating && _c.value == 0) {
          reduce ? _c.value = 1 : _c.forward();
          // Phones show the newest weeks first.
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (_scroll.hasClients) {
              _scroll.jumpTo(_scroll.position.maxScrollExtent);
            }
          });
        }
        return LayoutBuilder(
          builder: (context, box) {
            const labelW = 34.0;
            final cell = ((box.maxWidth - labelW) / _weeks - _gap).clamp(
              11.0,
              20.0,
            );
            final gridW = _weeks * (cell + _gap);
            final h = 7 * (cell + _gap);
            final grid = SizedBox(
              width: gridW,
              height: h + 24,
              child: Stack(
                clipBehavior: Clip.none,
                children: [
                  for (var m = 0; m < _weeks; m++)
                    if (_monthStart(m))
                      Positioned(
                        left: m * (cell + _gap),
                        top: 0,
                        child: Text(
                          _month(_date(m * 7)),
                          style: SLType.label(SLColors.inkMuted),
                        ),
                      ),
                  Positioned(
                    top: 24,
                    left: 0,
                    child: MouseRegion(
                      onExit: (_) => setState(() => _hover = null),
                      onHover: (e) {
                        final w = (e.localPosition.dx / (cell + _gap)).floor();
                        final d = (e.localPosition.dy / (cell + _gap)).floor();
                        final i = w * 7 + d;
                        final ok =
                            w >= 0 &&
                            w < _weeks &&
                            d >= 0 &&
                            d < 7 &&
                            _shown(i);
                        if ((ok ? i : null) != _hover) {
                          setState(() => _hover = ok ? i : null);
                        }
                      },
                      child: AnimatedBuilder(
                        animation: _c,
                        builder: (context, _) => CustomPaint(
                          size: Size(gridW, h),
                          painter: _GridPainter(
                            cell: cell,
                            t: _c.value,
                            hover: _hover,
                            shown: _shown,
                            count: (i) => commitDays[_key(_date(i))] ?? 0,
                          ),
                        ),
                      ),
                    ),
                  ),
                  if (_hover != null) _tooltip(_hover!, cell),
                ],
              ),
            );
            return Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(
                  width: labelW,
                  child: Padding(
                    padding: const EdgeInsets.only(top: 24),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        for (final d in ['', 'Mon', '', 'Wed', '', 'Fri', ''])
                          SizedBox(
                            height: cell + _gap,
                            child: Text(
                              d,
                              style: SLType.label(
                                SLColors.inkMuted,
                              ).copyWith(fontSize: 10, letterSpacing: 0),
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SingleChildScrollView(
                        controller: _scroll,
                        scrollDirection: Axis.horizontal,
                        child: grid,
                      ),
                      const SizedBox(height: 12),
                      const _Legend(),
                    ],
                  ),
                ),
              ],
            );
          },
        );
      },
    );
  }

  bool _shown(int i) => !_date(i).isAfter(DateTime.now());

  bool _monthStart(int w) =>
      w == 0 || _date(w * 7).month != _date((w - 1) * 7).month;

  static const _months = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];
  String _month(DateTime d) => _months[d.month - 1];

  Widget _tooltip(int i, double cell) {
    final d = _date(i);
    final n = commitDays[_key(d)] ?? 0;
    final x = (i ~/ 7) * (cell + _gap);
    final y = 24 + (i % 7) * (cell + _gap);
    return Positioned(
      left: (x - 44).clamp(0.0, double.infinity),
      top: y - 38,
      child: IgnorePointer(
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: BoxDecoration(
            color: SLColors.surface,
            border: Border.all(color: SLColors.hairline),
          ),
          child: Text(
            '${n == 0 ? 'No commits' : '$n commit${n == 1 ? '' : 's'}'}  ·  ${_month(d)} ${d.day}',
            style: SLType.label(SLColors.ink),
          ),
        ),
      ),
    );
  }
}

Color _levelColor(int n) {
  if (n == 0) return Colors.white.withValues(alpha: 0.06);
  final level = n >= 8
      ? 4
      : n >= 4
      ? 3
      : n >= 2
      ? 2
      : 1;
  return Color.lerp(
    const Color(0xFF5A3F0A),
    SLColors.accentHover,
    (level - 1) / 3,
  )!;
}

class _GridPainter extends CustomPainter {
  final double cell, t;
  final int? hover;
  final bool Function(int) shown;
  final int Function(int) count;
  _GridPainter({
    required this.cell,
    required this.t,
    required this.hover,
    required this.shown,
    required this.count,
  });

  @override
  void paint(Canvas canvas, Size size) {
    for (var w = 0; w < _weeks; w++) {
      for (var d = 0; d < 7; d++) {
        final i = w * 7 + d;
        if (!shown(i)) continue;
        // A wave crossing left to right, each square catching a beat after
        // its neighbour; the busiest days flare as they land.
        final start = (w + d * 0.35) / (_weeks + 3);
        final p = const Cubic(
          0.16,
          1,
          0.3,
          1,
        ).transform(((t * 1.5 - start * 1.0) / 0.5).clamp(0.0, 1.0));
        if (p <= 0) continue;
        final n = count(i);
        final c = _levelColor(n);
        final s = cell * (0.3 + 0.7 * p);
        final o = Offset(
          w * (cell + _gap) + (cell - s) / 2,
          d * (cell + _gap) + (cell - s) / 2,
        );
        final r = RRect.fromRectAndRadius(
          Rect.fromLTWH(o.dx, o.dy, s, s),
          Radius.circular(cell * 0.2),
        );
        if (n >= 4) {
          canvas.drawRRect(
            r,
            Paint()
              ..color = SLColors.accent.withValues(alpha: 0.35 * p)
              ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 4),
          );
        }
        canvas.drawRRect(r, Paint()..color = c.withValues(alpha: c.a * p));
        if (hover == i) {
          canvas.drawRRect(
            r.inflate(1.5),
            Paint()
              ..style = PaintingStyle.stroke
              ..strokeWidth = 1.5
              ..color = SLColors.ink,
          );
        }
      }
    }
  }

  @override
  bool shouldRepaint(_GridPainter old) => old.t != t || old.hover != hover;
}

class _Legend extends StatelessWidget {
  const _Legend();

  @override
  Widget build(BuildContext context) => Row(
    mainAxisAlignment: MainAxisAlignment.end,
    children: [
      Text('LESS', style: SLType.label(SLColors.inkMuted)),
      const SizedBox(width: 8),
      for (final n in [0, 1, 2, 4, 8])
        Container(
          width: 11,
          height: 11,
          margin: const EdgeInsets.only(right: 3),
          decoration: BoxDecoration(
            color: _levelColor(n),
            borderRadius: BorderRadius.circular(2),
          ),
        ),
      const SizedBox(width: 5),
      Text('MORE', style: SLType.label(SLColors.inkMuted)),
    ],
  );
}

// ------------------------------------------------------- where it went

/// Commits per project, as bars that fill in the project's own color when
/// scrolled to, led by its real icon.
class _WhereItWent extends StatelessWidget {
  const _WhereItWent();

  @override
  Widget build(BuildContext context) {
    final narrow = MediaQuery.sizeOf(context).width < 760;
    final max = commitsByProject.values.reduce((a, b) => a > b ? a : b);
    final rows = commitsByProject.entries.toList();
    return SLPage(
      padding: EdgeInsets.fromLTRB(24, narrow ? 56 : 88, 24, narrow ? 56 : 88),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          FadeSlideIn(
            child: Text(
              'Where the work went.',
              style: SLType.display(narrow ? 44 : 64),
            ),
          ),
          SizedBox(height: narrow ? 28 : 44),
          for (var i = 0; i < rows.length; i++)
            FadeSlideIn(
              index: i % 4,
              child: _ProjectBar(
                name: rows[i].key,
                count: rows[i].value,
                frac: rows[i].value / max,
                narrow: narrow,
              ),
            ),
        ],
      ),
    );
  }
}

class _ProjectBar extends StatelessWidget {
  final String name;
  final int count;
  final double frac;
  final bool narrow;
  const _ProjectBar({
    required this.name,
    required this.count,
    required this.frac,
    required this.narrow,
  });

  @override
  Widget build(BuildContext context) {
    final product = products
        .where((p) => p.name.toLowerCase() == name)
        .firstOrNull;
    final color = lineInk(product?.accent ?? SLColors.accent);
    final reduce = MediaQuery.disableAnimationsOf(context);
    final label = product?.name ?? 'Studio & tools';
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: Row(
        children: [
          if (product != null)
            AppIcon(product: product, size: narrow ? 32 : 40)
          else
            Container(
              width: narrow ? 32 : 40,
              height: narrow ? 32 : 40,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(
                  (narrow ? 32 : 40) * 0.2237,
                ),
                border: Border.all(color: SLColors.accent, width: 1.4),
              ),
              alignment: Alignment.center,
              child: Text('SL', style: SLType.label(SLColors.accent)),
            ),
          SizedBox(width: narrow ? 12 : 18),
          SizedBox(
            width: narrow ? 92 : 150,
            child: Text(
              label,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: SLType.display(narrow ? 20 : 26),
            ),
          ),
          Expanded(
            child: WhenVisible(
              builder: (context, visible) => TweenAnimationBuilder<double>(
                tween: Tween(
                  begin: reduce ? frac : 0,
                  end: visible || reduce ? frac : 0,
                ),
                duration: const Duration(milliseconds: 1300),
                curve: const Cubic(0.16, 1, 0.3, 1),
                builder: (_, v, _) => SizedBox(
                  height: 14,
                  child: CustomPaint(
                    size: const Size(double.infinity, 14),
                    painter: _BarPainter(v, color),
                  ),
                ),
              ),
            ),
          ),
          SizedBox(
            width: 52,
            child: Text(
              '$count',
              textAlign: TextAlign.right,
              style: SLType.label(SLColors.ink),
            ),
          ),
        ],
      ),
    );
  }
}

/// Segmented like the grid above: lit blocks to the value, unlit track after.
class _BarPainter extends CustomPainter {
  final double v;
  final Color color;
  _BarPainter(this.v, this.color);

  @override
  void paint(Canvas canvas, Size size) {
    const n = 48;
    const gap = 2.0;
    final w = (size.width - gap * (n - 1)) / n;
    final on = (v * n).ceil();
    for (var i = 0; i < n; i++) {
      final r = RRect.fromRectAndRadius(
        Rect.fromLTWH(i * (w + gap), 0, w, size.height),
        const Radius.circular(2),
      );
      if (i < on) {
        canvas.drawRRect(
          r,
          Paint()..color = color.withValues(alpha: 0.35 + 0.65 * (i / n)),
        );
      } else {
        canvas.drawRRect(
          r,
          Paint()..color = Colors.white.withValues(alpha: 0.06),
        );
      }
    }
  }

  @override
  bool shouldRepaint(_BarPainter old) => old.v != v || old.color != color;
}

class _Principles extends StatelessWidget {
  const _Principles();

  static const _items = [
    (
      'Coherence over breadth',
      'One studio\'s taste across every product, not nine unrelated experiments.',
    ),
    (
      'Built end to end',
      'Design, code, and ship — one person accountable for every product in the web.',
    ),
    (
      'Quality over speed',
      'A product ships when it is ready, not when a deadline says so.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return SLPage(
      padding: const EdgeInsets.fromLTRB(24, 64, 24, 96),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SizedBox(width: double.infinity),
          for (var i = 0; i < _items.length; i++)
            FadeSlideIn(
              index: i,
              child: Padding(
                padding: EdgeInsets.only(
                  bottom: i == _items.length - 1 ? 0 : 34,
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // The studio's own node, at text scale — the same marker
                    // the hub's web and lineup use, so a principle reads as
                    // part of the same system rather than a list item.
                    Container(
                      width: 9,
                      height: 9,
                      margin: const EdgeInsets.only(top: 8, right: 18),
                      decoration: const BoxDecoration(
                        shape: BoxShape.circle,
                        color: SLColors.accent,
                      ),
                    ),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(_items[i].$1, style: SLType.display(20)),
                          const SizedBox(height: 6),
                          ConstrainedBox(
                            constraints: const BoxConstraints(maxWidth: 560),
                            child: Text(_items[i].$2, style: SLType.body(15)),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }
}
