#!/usr/bin/env python3
"""Regenerates lib/data/activity.dart from the real git history of the
sibling project repos (run from anywhere): python3 tool/gen_activity.py"""
import subprocess, pathlib, collections, datetime

ROOT = pathlib.Path(__file__).resolve().parents[2]
GROUPS = {
    'workit': ['workit'], 'travelsync': ['travelsync', 'travelsync_website'],
    'plansync': ['plansync'], 'notesync': ['notesync', 'quire'],
    'diamo': ['diamo'], 'stanverse': ['stanverse'],
    'famfi': ['juwa_wealth', 'wealthsync', 'wealthsync_website'],
    'esync': ['esync'], 'dressmeup': ['dressmeup'], 'hoopsync': ['hoopsync'],
    'jarvis': ['jarvis'], 'studio': ['supremolabs', 'papersync', 'singit', 'winsnap'],
}
today = datetime.date.today()
start = today - datetime.timedelta(days=today.weekday() + 1 + 52 * 7)  # a Sunday
days, by = collections.Counter(), collections.Counter()
for g, repos in GROUPS.items():
    for r in repos:
        p = ROOT / r
        if not (p / '.git').exists():
            continue
        out = subprocess.run(['git', '-C', str(p), 'log', '--all', '--format=%H %ad', '--date=short'],
                             capture_output=True, text=True).stdout.split('\n')
        seen = set()
        for line in out:
            if not line.strip():
                continue
            h, d = line.split()
            if h in seen or datetime.date.fromisoformat(d) < start:
                continue
            seen.add(h); days[d] += 1; by[g] += 1
lines = ["// GENERATED by tool/gen_activity.py from real git history. Do not edit.",
         f"final activityStart = DateTime({start.year}, {start.month}, {start.day});",
         "const commitDays = <String, int>{"]
lines += [f"  '{d}': {n}," for d, n in sorted(days.items())]
lines += ["};", "", "const commitsByProject = <String, int>{"]
lines += [f"  '{g}': {n}," for g, n in by.most_common()]
lines += ["};", ""]
(ROOT / 'supremolabs/lib/data/activity.dart').write_text('\n'.join(lines))
print(sum(days.values()), 'commits', len(days), 'active days', dict(by))
